services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_filament_app
    container_name: laravel_filament_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - laravel_filament_net

  db:
    image: mysql:8.0.39
    container_name: laravel_filament_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - db_data:/var/lib/mysql/
    networks:
      - laravel_filament_net

  web:
    image: nginx:alpine
    container_name: laravel_filament_web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_filament_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_filament_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: secret
    networks:
      - laravel_filament_net

volumes:
  db_data:

networks:
  laravel_filament_net:
    driver: bridge
